
name: test
on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.12.0" 
      
      - run: npm ci

      - name: run tests
        if: always()
        run:
          npm run wdio